# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tracking_pb2 as tracking__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tracking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObject = channel.unary_unary(
                '/tracking.TrackingService/DetectObject',
                request_serializer=tracking__pb2.DetectionRequest.SerializeToString,
                response_deserializer=tracking__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/tracking.TrackingService/GetEmbedding',
                request_serializer=tracking__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=tracking__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/tracking.TrackingService/Chat',
                request_serializer=tracking__pb2.ChatRequest.SerializeToString,
                response_deserializer=tracking__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.VoiceChat = channel.unary_unary(
                '/tracking.TrackingService/VoiceChat',
                request_serializer=tracking__pb2.VoiceChatRequest.SerializeToString,
                response_deserializer=tracking__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamFrame = channel.unary_unary(
                '/tracking.TrackingService/StreamFrame',
                request_serializer=tracking__pb2.FrameRequest.SerializeToString,
                response_deserializer=tracking__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.VoiceChatStream = channel.stream_stream(
                '/tracking.TrackingService/VoiceChatStream',
                request_serializer=tracking__pb2.VoiceChatChunk.SerializeToString,
                response_deserializer=tracking__pb2.AudioChunk.FromString,
                _registered_method=True)


class TrackingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceChatStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObject,
                    request_deserializer=tracking__pb2.DetectionRequest.FromString,
                    response_serializer=tracking__pb2.DetectionResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=tracking__pb2.EmbeddingRequest.FromString,
                    response_serializer=tracking__pb2.EmbeddingResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=tracking__pb2.ChatRequest.FromString,
                    response_serializer=tracking__pb2.ChatResponse.SerializeToString,
            ),
            'VoiceChat': grpc.unary_unary_rpc_method_handler(
                    servicer.VoiceChat,
                    request_deserializer=tracking__pb2.VoiceChatRequest.FromString,
                    response_serializer=tracking__pb2.ChatResponse.SerializeToString,
            ),
            'StreamFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamFrame,
                    request_deserializer=tracking__pb2.FrameRequest.FromString,
                    response_serializer=tracking__pb2.FrameResponse.SerializeToString,
            ),
            'VoiceChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.VoiceChatStream,
                    request_deserializer=tracking__pb2.VoiceChatChunk.FromString,
                    response_serializer=tracking__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/DetectObject',
            tracking__pb2.DetectionRequest.SerializeToString,
            tracking__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/GetEmbedding',
            tracking__pb2.EmbeddingRequest.SerializeToString,
            tracking__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/Chat',
            tracking__pb2.ChatRequest.SerializeToString,
            tracking__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoiceChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/VoiceChat',
            tracking__pb2.VoiceChatRequest.SerializeToString,
            tracking__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/StreamFrame',
            tracking__pb2.FrameRequest.SerializeToString,
            tracking__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoiceChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tracking.TrackingService/VoiceChatStream',
            tracking__pb2.VoiceChatChunk.SerializeToString,
            tracking__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrameWithGuidance = channel.unary_unary(
                '/tracking.MediatorService/StreamFrameWithGuidance',
                request_serializer=tracking__pb2.FrameRequest.SerializeToString,
                response_deserializer=tracking__pb2.GuidanceFrameResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/tracking.MediatorService/Chat',
                request_serializer=tracking__pb2.ChatRequest.SerializeToString,
                response_deserializer=tracking__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.VoiceChat = channel.unary_unary(
                '/tracking.MediatorService/VoiceChat',
                request_serializer=tracking__pb2.VoiceChatRequest.SerializeToString,
                response_deserializer=tracking__pb2.ChatResponse.FromString,
                _registered_method=True)


class MediatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrameWithGuidance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrameWithGuidance': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamFrameWithGuidance,
                    request_deserializer=tracking__pb2.FrameRequest.FromString,
                    response_serializer=tracking__pb2.GuidanceFrameResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=tracking__pb2.ChatRequest.FromString,
                    response_serializer=tracking__pb2.ChatResponse.SerializeToString,
            ),
            'VoiceChat': grpc.unary_unary_rpc_method_handler(
                    servicer.VoiceChat,
                    request_deserializer=tracking__pb2.VoiceChatRequest.FromString,
                    response_serializer=tracking__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.MediatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.MediatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrameWithGuidance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MediatorService/StreamFrameWithGuidance',
            tracking__pb2.FrameRequest.SerializeToString,
            tracking__pb2.GuidanceFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MediatorService/Chat',
            tracking__pb2.ChatRequest.SerializeToString,
            tracking__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoiceChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MediatorService/VoiceChat',
            tracking__pb2.VoiceChatRequest.SerializeToString,
            tracking__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MapServiceStub(object):
    """── Map service ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMaps = channel.unary_unary(
                '/tracking.MapService/ListMaps',
                request_serializer=tracking__pb2.ListMapsRequest.SerializeToString,
                response_deserializer=tracking__pb2.ListMapsResponse.FromString,
                _registered_method=True)
        self.GetMapGeometry = channel.unary_stream(
                '/tracking.MapService/GetMapGeometry',
                request_serializer=tracking__pb2.GetMapRequest.SerializeToString,
                response_deserializer=tracking__pb2.MapGeometryChunk.FromString,
                _registered_method=True)
        self.ScanFrame = channel.unary_unary(
                '/tracking.MapService/ScanFrame',
                request_serializer=tracking__pb2.ScanFrameRequest.SerializeToString,
                response_deserializer=tracking__pb2.ScanFrameResponse.FromString,
                _registered_method=True)
        self.SetZoneLabel = channel.unary_unary(
                '/tracking.MapService/SetZoneLabel',
                request_serializer=tracking__pb2.SetZoneLabelRequest.SerializeToString,
                response_deserializer=tracking__pb2.SetZoneLabelResponse.FromString,
                _registered_method=True)
        self.ExportScanMap = channel.unary_unary(
                '/tracking.MapService/ExportScanMap',
                request_serializer=tracking__pb2.ExportScanMapRequest.SerializeToString,
                response_deserializer=tracking__pb2.ExportScanMapResponse.FromString,
                _registered_method=True)


class MapServiceServicer(object):
    """── Map service ────────────────────────────────────────────────────────────

    """

    def ListMaps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapGeometry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetZoneLabel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportScanMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMaps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaps,
                    request_deserializer=tracking__pb2.ListMapsRequest.FromString,
                    response_serializer=tracking__pb2.ListMapsResponse.SerializeToString,
            ),
            'GetMapGeometry': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMapGeometry,
                    request_deserializer=tracking__pb2.GetMapRequest.FromString,
                    response_serializer=tracking__pb2.MapGeometryChunk.SerializeToString,
            ),
            'ScanFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanFrame,
                    request_deserializer=tracking__pb2.ScanFrameRequest.FromString,
                    response_serializer=tracking__pb2.ScanFrameResponse.SerializeToString,
            ),
            'SetZoneLabel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZoneLabel,
                    request_deserializer=tracking__pb2.SetZoneLabelRequest.FromString,
                    response_serializer=tracking__pb2.SetZoneLabelResponse.SerializeToString,
            ),
            'ExportScanMap': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportScanMap,
                    request_deserializer=tracking__pb2.ExportScanMapRequest.FromString,
                    response_serializer=tracking__pb2.ExportScanMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.MapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.MapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapService(object):
    """── Map service ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def ListMaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MapService/ListMaps',
            tracking__pb2.ListMapsRequest.SerializeToString,
            tracking__pb2.ListMapsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMapGeometry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tracking.MapService/GetMapGeometry',
            tracking__pb2.GetMapRequest.SerializeToString,
            tracking__pb2.MapGeometryChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MapService/ScanFrame',
            tracking__pb2.ScanFrameRequest.SerializeToString,
            tracking__pb2.ScanFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetZoneLabel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MapService/SetZoneLabel',
            tracking__pb2.SetZoneLabelRequest.SerializeToString,
            tracking__pb2.SetZoneLabelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportScanMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MapService/ExportScanMap',
            tracking__pb2.ExportScanMapRequest.SerializeToString,
            tracking__pb2.ExportScanMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
