# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tracking_pb2 as tracking__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tracking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackingServiceStub(object):
    """Android is the only client this server talks to (see CLAUDE.md's
    "Client-Orchestrated Live Session" section) — the Pi thin client,
    Mediator, Desktop operator GUI, and offline-scan workflow (and every RPC/
    message that existed only for them: MediatorService, the old MapService,
    TrackingService's Chat/VoiceChat/VoiceChatStream/StreamFrame) have been
    removed. Gemini Live orchestration runs entirely on-device now; this
    server is a pure heavy-compute + live-mapping backend.

    DetectObject/GetEmbedding stay heavy models called directly by Android's
    TrackingBackend.kt for its local-ORB-tracking init/renewal — not merged
    into PerceptionService.AnalyzeFrame since that call site predates it and
    still works unchanged.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObject = channel.unary_unary(
                '/tracking.TrackingService/DetectObject',
                request_serializer=tracking__pb2.DetectionRequest.SerializeToString,
                response_deserializer=tracking__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/tracking.TrackingService/GetEmbedding',
                request_serializer=tracking__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=tracking__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class TrackingServiceServicer(object):
    """Android is the only client this server talks to (see CLAUDE.md's
    "Client-Orchestrated Live Session" section) — the Pi thin client,
    Mediator, Desktop operator GUI, and offline-scan workflow (and every RPC/
    message that existed only for them: MediatorService, the old MapService,
    TrackingService's Chat/VoiceChat/VoiceChatStream/StreamFrame) have been
    removed. Gemini Live orchestration runs entirely on-device now; this
    server is a pure heavy-compute + live-mapping backend.

    DetectObject/GetEmbedding stay heavy models called directly by Android's
    TrackingBackend.kt for its local-ORB-tracking init/renewal — not merged
    into PerceptionService.AnalyzeFrame since that call site predates it and
    still works unchanged.
    """

    def DetectObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObject,
                    request_deserializer=tracking__pb2.DetectionRequest.FromString,
                    response_serializer=tracking__pb2.DetectionResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=tracking__pb2.EmbeddingRequest.FromString,
                    response_serializer=tracking__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Android is the only client this server talks to (see CLAUDE.md's
    "Client-Orchestrated Live Session" section) — the Pi thin client,
    Mediator, Desktop operator GUI, and offline-scan workflow (and every RPC/
    message that existed only for them: MediatorService, the old MapService,
    TrackingService's Chat/VoiceChat/VoiceChatStream/StreamFrame) have been
    removed. Gemini Live orchestration runs entirely on-device now; this
    server is a pure heavy-compute + live-mapping backend.

    DetectObject/GetEmbedding stay heavy models called directly by Android's
    TrackingBackend.kt for its local-ORB-tracking init/renewal — not merged
    into PerceptionService.AnalyzeFrame since that call site predates it and
    still works unchanged.
    """

    @staticmethod
    def DetectObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/DetectObject',
            tracking__pb2.DetectionRequest.SerializeToString,
            tracking__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.TrackingService/GetEmbedding',
            tracking__pb2.EmbeddingRequest.SerializeToString,
            tracking__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PerceptionServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────
    PerceptionService / MappingService

    Consolidated heavy-compute surface for the Android client's on-device
    Gemini Live tool-dispatch loop — see CLAUDE.md's "Client-Orchestrated
    Live Session" section.
    ─────────────────────────────────────────────────────────────────────────

    Heavy, stateless-per-call perception primitives: object detection,
    re-ID embedding, obstacle/depth estimation, neural TTS, text embedding.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFrame = channel.unary_unary(
                '/tracking.PerceptionService/AnalyzeFrame',
                request_serializer=tracking__pb2.AnalyzeFrameRequest.SerializeToString,
                response_deserializer=tracking__pb2.AnalyzeFrameResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_stream(
                '/tracking.PerceptionService/Synthesize',
                request_serializer=tracking__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tracking__pb2.PcmChunk.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/tracking.PerceptionService/Embed',
                request_serializer=tracking__pb2.EmbedRequest.SerializeToString,
                response_deserializer=tracking__pb2.EmbedResponse.FromString,
                _registered_method=True)


class PerceptionServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────
    PerceptionService / MappingService

    Consolidated heavy-compute surface for the Android client's on-device
    Gemini Live tool-dispatch loop — see CLAUDE.md's "Client-Orchestrated
    Live Session" section.
    ─────────────────────────────────────────────────────────────────────────

    Heavy, stateless-per-call perception primitives: object detection,
    re-ID embedding, obstacle/depth estimation, neural TTS, text embedding.
    """

    def AnalyzeFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFrame,
                    request_deserializer=tracking__pb2.AnalyzeFrameRequest.FromString,
                    response_serializer=tracking__pb2.AnalyzeFrameResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tracking__pb2.SynthesizeRequest.FromString,
                    response_serializer=tracking__pb2.PcmChunk.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=tracking__pb2.EmbedRequest.FromString,
                    response_serializer=tracking__pb2.EmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.PerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.PerceptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerceptionService(object):
    """─────────────────────────────────────────────────────────────────────────
    PerceptionService / MappingService

    Consolidated heavy-compute surface for the Android client's on-device
    Gemini Live tool-dispatch loop — see CLAUDE.md's "Client-Orchestrated
    Live Session" section.
    ─────────────────────────────────────────────────────────────────────────

    Heavy, stateless-per-call perception primitives: object detection,
    re-ID embedding, obstacle/depth estimation, neural TTS, text embedding.
    """

    @staticmethod
    def AnalyzeFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.PerceptionService/AnalyzeFrame',
            tracking__pb2.AnalyzeFrameRequest.SerializeToString,
            tracking__pb2.AnalyzeFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tracking.PerceptionService/Synthesize',
            tracking__pb2.SynthesizeRequest.SerializeToString,
            tracking__pb2.PcmChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.PerceptionService/Embed',
            tracking__pb2.EmbedRequest.SerializeToString,
            tracking__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MappingServiceStub(object):
    """Live SLAM-style mapping + localization, active whenever the client's
    guiding/walking mode is on (there is no separate offline "scan session"
    any more — see CLAUDE.md's "3D Scanning Pipeline" section).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMapping = channel.stream_stream(
                '/tracking.MappingService/UpdateMapping',
                request_serializer=tracking__pb2.MappingChunk.SerializeToString,
                response_deserializer=tracking__pb2.MappingUpdate.FromString,
                _registered_method=True)
        self.GetMapSnapshot = channel.unary_unary(
                '/tracking.MappingService/GetMapSnapshot',
                request_serializer=tracking__pb2.GetMapSnapshotRequest.SerializeToString,
                response_deserializer=tracking__pb2.MapSnapshot.FromString,
                _registered_method=True)
        self.ListMappedLocations = channel.unary_unary(
                '/tracking.MappingService/ListMappedLocations',
                request_serializer=tracking__pb2.ListMapsRequest.SerializeToString,
                response_deserializer=tracking__pb2.ListMapsResponse.FromString,
                _registered_method=True)
        self.FindLandmark = channel.unary_unary(
                '/tracking.MappingService/FindLandmark',
                request_serializer=tracking__pb2.FindLandmarkRequest.SerializeToString,
                response_deserializer=tracking__pb2.FindLandmarkResponse.FromString,
                _registered_method=True)


class MappingServiceServicer(object):
    """Live SLAM-style mapping + localization, active whenever the client's
    guiding/walking mode is on (there is no separate offline "scan session"
    any more — see CLAUDE.md's "3D Scanning Pipeline" section).
    """

    def UpdateMapping(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMappedLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindLandmark(self, request, context):
        """Deferred landmark lookup: GroundingDINO never runs proactively during
        scanning any more (see scan_server/semantic_mapper.py's module
        docstring) — this is the only place it runs, on demand, against the
        session's in-memory frame store (tag-match first, else a first-hit
        scan — see scan_server/scan_session.py's resolve_landmark()). Because
        MappingUpdate.landmarks now stays empty for the duration of an active
        stream (real positions only exist after finalize-time export or via
        this RPC), the Android client always resolves a guiding destination
        through this call rather than a live-streamed landmarks list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MappingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMapping': grpc.stream_stream_rpc_method_handler(
                    servicer.UpdateMapping,
                    request_deserializer=tracking__pb2.MappingChunk.FromString,
                    response_serializer=tracking__pb2.MappingUpdate.SerializeToString,
            ),
            'GetMapSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapSnapshot,
                    request_deserializer=tracking__pb2.GetMapSnapshotRequest.FromString,
                    response_serializer=tracking__pb2.MapSnapshot.SerializeToString,
            ),
            'ListMappedLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMappedLocations,
                    request_deserializer=tracking__pb2.ListMapsRequest.FromString,
                    response_serializer=tracking__pb2.ListMapsResponse.SerializeToString,
            ),
            'FindLandmark': grpc.unary_unary_rpc_method_handler(
                    servicer.FindLandmark,
                    request_deserializer=tracking__pb2.FindLandmarkRequest.FromString,
                    response_serializer=tracking__pb2.FindLandmarkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.MappingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.MappingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MappingService(object):
    """Live SLAM-style mapping + localization, active whenever the client's
    guiding/walking mode is on (there is no separate offline "scan session"
    any more — see CLAUDE.md's "3D Scanning Pipeline" section).
    """

    @staticmethod
    def UpdateMapping(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tracking.MappingService/UpdateMapping',
            tracking__pb2.MappingChunk.SerializeToString,
            tracking__pb2.MappingUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMapSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MappingService/GetMapSnapshot',
            tracking__pb2.GetMapSnapshotRequest.SerializeToString,
            tracking__pb2.MapSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMappedLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MappingService/ListMappedLocations',
            tracking__pb2.ListMapsRequest.SerializeToString,
            tracking__pb2.ListMapsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindLandmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.MappingService/FindLandmark',
            tracking__pb2.FindLandmarkRequest.SerializeToString,
            tracking__pb2.FindLandmarkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StatusServiceStub(object):
    """StatusService — the server has no other way to know what mode the client
    is in (no server-side session/LiveSessionState any more — orchestration
    runs on Android, see CLAUDE.md's "Client-Orchestrated Live Session"
    section). ToolDispatcher.kt calls ReportMode once per LiveSessionState.mode
    transition purely so server_gui.py's dashboard can display/select the
    correct tab directly instead of inferring it from whichever RPC category
    last happened to fire — this RPC carries no data any other service needs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportMode = channel.unary_unary(
                '/tracking.StatusService/ReportMode',
                request_serializer=tracking__pb2.ReportModeRequest.SerializeToString,
                response_deserializer=tracking__pb2.ReportModeResponse.FromString,
                _registered_method=True)
        self.ReportBeaconDirection = channel.unary_unary(
                '/tracking.StatusService/ReportBeaconDirection',
                request_serializer=tracking__pb2.ReportBeaconDirectionRequest.SerializeToString,
                response_deserializer=tracking__pb2.ReportBeaconDirectionResponse.FromString,
                _registered_method=True)


class StatusServiceServicer(object):
    """StatusService — the server has no other way to know what mode the client
    is in (no server-side session/LiveSessionState any more — orchestration
    runs on Android, see CLAUDE.md's "Client-Orchestrated Live Session"
    section). ToolDispatcher.kt calls ReportMode once per LiveSessionState.mode
    transition purely so server_gui.py's dashboard can display/select the
    correct tab directly instead of inferring it from whichever RPC category
    last happened to fire — this RPC carries no data any other service needs.
    """

    def ReportMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBeaconDirection(self, request, context):
        """Dashboard-only, fire-and-forget, same precedent as ReportMode above —
        carries no data any other service needs. The server has no other way
        to learn the beacon's actual final azimuth: goal-biasing + EMA
        smoothing now happen client-side (see ToolDispatcher's local-avoidance
        tick), so server_gui.py can't reconstruct it from the raw
        TraversabilityInfo fan alone. Called once per avoidance tick while
        walking/guiding is active.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportMode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMode,
                    request_deserializer=tracking__pb2.ReportModeRequest.FromString,
                    response_serializer=tracking__pb2.ReportModeResponse.SerializeToString,
            ),
            'ReportBeaconDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBeaconDirection,
                    request_deserializer=tracking__pb2.ReportBeaconDirectionRequest.FromString,
                    response_serializer=tracking__pb2.ReportBeaconDirectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.StatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracking.StatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatusService(object):
    """StatusService — the server has no other way to know what mode the client
    is in (no server-side session/LiveSessionState any more — orchestration
    runs on Android, see CLAUDE.md's "Client-Orchestrated Live Session"
    section). ToolDispatcher.kt calls ReportMode once per LiveSessionState.mode
    transition purely so server_gui.py's dashboard can display/select the
    correct tab directly instead of inferring it from whichever RPC category
    last happened to fire — this RPC carries no data any other service needs.
    """

    @staticmethod
    def ReportMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.StatusService/ReportMode',
            tracking__pb2.ReportModeRequest.SerializeToString,
            tracking__pb2.ReportModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportBeaconDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracking.StatusService/ReportBeaconDirection',
            tracking__pb2.ReportBeaconDirectionRequest.SerializeToString,
            tracking__pb2.ReportBeaconDirectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
